package br.com.tnt.ssg.dao.factory;

public enum EntityTypeEnum {

	AGENDAMENTO_SERVICO, AUTONOMO, AVALIACAO, CATEGORIA, CIDADE, CIDADE_SERVICO, CLIENTE, CONTATO, PERMISSAO, SERVICO, SOLICITACAO_SERVICO, UF, USUARIO, USUARIO_PERMISSAO
}
